sylius_grid:
    grids:
        setono_sylius_analytics_plugin_admin_product_analytic:
            driver:
                options:
                    class: "%setono_sylius_analytics_plugin.model.analytic.class%"
            fields:
                name:
                    type: string
                    label: setono_sylius_analytics_plugin.ui.name
                enabled:
                    type: twig
                    label: setono_sylius_analytics_plugin.ui.enabled
                    options:
                        template: SyliusUiBundle:Grid/Field:enabled.html.twig
            filters:
                name:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
