services:
    setono_sylius_analytics_plugin.context.config:
        class: Setono\SyliusAnalyticsPlugin\Context\AnalyticConfigContext
        public: true
        arguments:
        - "@setono_sylius_analytics.repository.analytic"
        - "@setono_sylius_analytics.factory.analytic"
