services:
    setono_sylius_analytics_plugin.context.config:
        class: Setono\SyliusAnalyticsPlugin\Context\AnalyticConfigContext
        public: true
        arguments:
        - "@setono_sylius_analytics.repository.google_analytics_config"
        - "@setono_sylius_analytics.factory.google_analytics_config"
