services:
    setono_sylius_analytics_plugin.event_listener.google_analytic:
        class: Setono\SyliusAnalyticsPlugin\EventListener\GoogleAnalyticEventListener
        arguments:
            - 'SetonoSyliusAnalyticsPlugin::google_analytic.html.twig'
            - "@setono_sylius_analytics_plugin.context.config"
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.stylesheets, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_add_payment_info:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\AddPaymentInfo.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.select_payment.before_form, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\AddToCart.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_add_to_cart, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_begin_checkout:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\BeginCheckout.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.cart.summary.before_suggestions, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_checkout_progress:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\CheckoutProgress.html.twig'
        tags:
        - { name: kernel.event_listener, event: sylius.shop.checkout.address.before_form, method: onBlockEvent }
        - { name: kernel.event_listener, event: sylius.shop.checkout.select.shipping.before_form, method: onBlockEvent }
        - { name: kernel.event_listener, event: sylius.shop.checkout.select.payment.before_form, method: onBlockEvent }
        - { name: kernel.event_listener, event: sylius.shop.checkout.complete.before_summary, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_purchase:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\Purchase.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.order.thank_you.after_message, method: onBlockEvent }

#    setono_sylius_analytics_plugin.event_listener.google_analytic_view_item:
#        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
#        arguments:
#        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\ViewItem.html.twig'
#        tags:
#        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_add_to_cart, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_login:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\Login.html.twig'
        tags:
        - { name: kernel.event_listener, event: sylius.shop.login.after_login, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_sign_up:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\SignUp.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.login.after_register, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_search:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\Search.html.twig'
        tags:
        - { name: kernel.event_listener, event: sylius.shop.product.index.after_search, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_select_content:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\SelectContent.html.twig'
        tags:
        - { name: kernel.event_listener, event: sylius.admin.customer.show.after_information, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_view_item_list:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\ViewItemList.html.twig'
        tags:
        - { name: kernel.event_listener, event: sylius.shop.product_review.index.after_list, method: onBlockEvent }



