services:
    setono_sylius_analytics_plugin.event_listener.google_analytic:
        class: Setono\SyliusAnalyticsPlugin\EventListener\GoogleAnalyticEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::google_analytic.html.twig'
        - "@setono_sylius_analytics_plugin.context.config"
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.stylesheets, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_add_payment_info:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\AddToCart.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.checkout.select_payment.before_form, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_add_to_cart:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\AddPaymentInfo.html.twig'
        tags:
        - { name: kernel.event_listener, event: event: sonata.block.event.sylius.shop.checkout.select_payment.before_form, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_begin_checkout:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\BeginCheckout.html.twig'
        tags:
        - { name: kernel.event_listener, event: event: sonata.block.event.sylius.shop.checkout.address.after_header, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_purchase:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\Purchase.html.twig'
        tags:
        - { name: kernel.event_listener, event: event: sonata.block.event.sylius.shop.order.thank_you.after_message, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_view_item:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\ViewItem.html.twig'
        tags:
        - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_add_to_cart, method: onBlockEvent }

    setono_sylius_analytics_plugin.event_listener.google_analytic_search:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
        - 'SetonoSyliusAnalyticsPlugin::GoogleAnalyticEvents\Search.html.twig'
