services:
    setono_sylius_analytics_plugin.listener.menu.analytic:
        class: Setono\SyliusAnalyticsPlugin\Menu\AnalyticsMenuBuilder
        arguments:
            - "@setono_sylius_analytics_plugin.context.config"
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAnalytics}

    setono_sylius_analytics_plugin.form.type.google_analytic_config:
        class: Setono\SyliusAnalyticsPlugin\Form\Type\GoogleAnalyticConfigType
        arguments:
        - "%setono_sylius_analytics_plugin.model.analytic.class%"
        - ['setono']
        tags:
        - { name: form.type }

    setono_sylius_analytics_plugin.form.type.translation.google_analytic_config:
        class: Setono\SyliusAnalyticsPlugin\Form\Type\Translation\GoogleAnalyticConfigTranslationType
        arguments:
        - "%setono_sylius_analytics_plugin.model.analytic_translation.class%"
        - ['setono']
        tags:
        - { name: form.type }
imports:
    - { resource: services/menu.yml }
    - { resource: services/event_listener.yml }
    - { resource: services/context.yml }
