imports:
- { resource: services/menu.yml }
- { resource: services/event_listener.yml }
- { resource: services/context.yml }

services:
    setono_sylius_analytics_plugin.listener.menu.google_analytic_config:
        class: Setono\SyliusAnalyticsPlugin\Menu\AnalyticsMenuBuilder
        arguments:
            - "@setono_sylius_analytics_plugin.context.config"
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAnalytics}

    setono_sylius_analytics_plugin.form.type.google_analytic_config:
        class: Setono\SyliusAnalyticsPlugin\Form\Type\GoogleAnalyticConfigType
        arguments:
        - "%setono_sylius_analytics.model.google_analytics_config.class%"
        - ['setono']
        tags:
        - { name: form.type }

