Setono\SyliusAnalyticsPlugin\Model\AnalyticsConfig:
    constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [trackingId]
          message: 'setono_sylius_analytics.analytics_config.tracking_id.unique'
          groups: ['setono']
    properties:
        trackingId:
        - NotBlank:
              message: 'setono_sylius_analytics.analytics_config.tracking_id.not_blank'
              groups: ['setono']
        - Length:
              min: 2
              max: 250
              minMessage: 'setono_sylius_analytics.analytics_config.tracking_id.min_length'
              maxMessage: 'setono_sylius_analytics.analytics_config.tracking_id.max_length'
              groups: ['setono']
