Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfigTranslation:
    properties:
        name:
        - NotBlank:
              message: 'setono_sylius_analytics_plugin.google_analytic_config.name.not_blank'
              groups: ['setono']
        - Length:
              min: 2
              max: 250
              minMessage: 'setono_sylius_analytics_plugin.google_analytic_config.name.min_length'
              maxMessage: 'setono_sylius_analytics_plugin.google_analytic_config.name.max_length'
              groups: ['setono']
