sylius_resource:
    resources:
        setono_sylius_analytics_plugin.analytic:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfig
                interface: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfigInterface
                repository: Setono\SyliusAnalyticsPlugin\Repository\AnalyticConfigRepository
                form: Setono\SyliusAnalyticsPlugin\Form\Type\GoogleAnalyticConfigType
            translation:
                classes:
                    model: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfigTranslation
                    interface: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfigTranslationInterface

