sylius_resource:
    resources:
        setono_sylius_analytics_plugin.analytic:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusAnalyticsPlugin\Model\GoogleAnalyticConfig
                interface: Setono\SyliusAnalyticsPlugin\Model\GoogleAnalyticConfigInterface
                repository: Setono\SyliusAnalyticsPlugin\Repository\AnalyticConfigRepository
                form: Setono\SyliusAnalyticsPlugin\Form\Type\GoogleAnalyticConfigType


