sylius_resource:
    resources:
        setono_sylius_analytics_plugin.analytic:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfig
                interface: Setono\SyliusAnalyticsPlugin\Entity\GoogleAnalyticConfigInterface
